/**
 * ISO-3166-1 alpha-2 für Stammdaten / Sendungserfassung (DB: CHAR(2)).
 * Umfasst europäische Staaten, EWR (IS, LI, NO neben EU), GB, angrenzend RU/TR,
 * gängige europäische Klein- und Sondergebiete.
 */
export const COUNTRY_CODE_OPTIONS: { value: string; label: string }[] = [
  { value: 'AL', label: 'Albanien' },
  { value: 'AD', label: 'Andorra' },
  { value: 'BY', label: 'Belarus' },
  { value: 'BE', label: 'Belgien' },
  { value: 'BA', label: 'Bosnien und Herzegowina' },
  { value: 'BG', label: 'Bulgarien' },
  { value: 'DK', label: 'Dänemark' },
  { value: 'DE', label: 'Deutschland' },
  { value: 'EE', label: 'Estland' },
  { value: 'FO', label: 'Färöer' },
  { value: 'FI', label: 'Finnland' },
  { value: 'FR', label: 'Frankreich' },
  { value: 'GI', label: 'Gibraltar' },
  { value: 'GR', label: 'Griechenland' },
  { value: 'GG', label: 'Guernsey' },
  { value: 'IE', label: 'Irland' },
  { value: 'IS', label: 'Island' },
  { value: 'IM', label: 'Isle of Man' },
  { value: 'IT', label: 'Italien' },
  { value: 'JE', label: 'Jersey' },
  { value: 'XK', label: 'Kosovo' },
  { value: 'HR', label: 'Kroatien' },
  { value: 'LV', label: 'Lettland' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Litauen' },
  { value: 'LU', label: 'Luxemburg' },
  { value: 'MT', label: 'Malta' },
  { value: 'MD', label: 'Moldau' },
  { value: 'MC', label: 'Monaco' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'NL', label: 'Niederlande' },
  { value: 'MK', label: 'Nordmazedonien' },
  { value: 'NO', label: 'Norwegen' },
  { value: 'AT', label: 'Österreich' },
  { value: 'PL', label: 'Polen' },
  { value: 'PT', label: 'Portugal' },
  { value: 'RO', label: 'Rumänien' },
  { value: 'RU', label: 'Russland' },
  { value: 'SM', label: 'San Marino' },
  { value: 'SE', label: 'Schweden' },
  { value: 'CH', label: 'Schweiz' },
  { value: 'RS', label: 'Serbien' },
  { value: 'SK', label: 'Slowakei' },
  { value: 'SI', label: 'Slowenien' },
  { value: 'ES', label: 'Spanien' },
  { value: 'CZ', label: 'Tschechien' },
  { value: 'TR', label: 'Türkei' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'HU', label: 'Ungarn' },
  { value: 'VA', label: 'Vatikanstadt' },
  { value: 'GB', label: 'Vereinigtes Königreich' },
  { value: 'CY', label: 'Zypern' },
];
